[tool.black]
line-length = 115

[tool.ruff]
line-length = 115

[tool.ruff.lint]
# https://github.com/astral-sh/ruff#supported-rules
select = ["E", "F", "T", "W"]
ignore = ["W292", "T201"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "ERROR"
asyncio_mode = "auto"

